import { useMemo } from "react";

export default function TermsPage({ agree, setAgree, onDecline, onNext, onBackToStart, onCancel }) {
  const termsSections = useMemo(
    () => [
      {
        title: "Terms and Conditions",
        paragraphs: [
          "By proceeding with the use of this Smart BMI Kiosk, you acknowledge that the system will collect and process certain personal and biometric information necessary for the operation of the service.",
          "The Smart BMI Kiosk collects personal information including your name, age, sex, height, weight, Body Mass Index (BMI) results, and facial image. The facial image captured by the camera is used for facial recognition to identify returning users and retrieve their previous BMI records. This allows the system to provide a more convenient experience by maintaining a history of BMI measurements for monitoring purposes.",
          "All information collected by the system is used solely for identification, BMI computation, record management, and research purposes related to this academic project. The data may be stored in a secure administrative database that is accessible only to authorized system administrators involved in the project.",
          "The system implements reasonable safeguards to protect personal data from unauthorized access, disclosure, alteration, or misuse. All collected information will be handled responsibly and processed in accordance with applicable data protection regulations, including the Data Privacy Act of 2012 (Republic Act No. 10173).",
        ],
      },
      {
        title: "Research Disclaimer",
        paragraphs: [
          "This Smart BMI Kiosk is developed as part of an academic thesis project. The system is intended for research, educational, and demonstration purposes only. The BMI results generated by the kiosk are informational and should not be considered a medical diagnosis or a substitute for professional medical advice. Users who require medical guidance should consult a qualified healthcare professional.",
        ],
      },
      {
        title: "Data Retention Policy",
        paragraphs: [
          "Personal data collected by the Smart BMI Kiosk will be stored only for the duration necessary to support the research objectives and system evaluation of this thesis project. The collected data may be retained for documentation, testing, and analysis purposes during the development and evaluation phase of the system. After the completion of the research project, data may be securely archived or deleted in accordance with institutional research policies and applicable data protection regulations.",
          "Authorized researchers and system administrators will be responsible for maintaining the confidentiality and security of all stored information.",
        ],
      },
      {
        title: "Contact Information",
        paragraphs: ["For questions, concerns, or requests related to your data or the use of this system, you may contact the research team at:"],
        email: "teamdynamos02@gmail.com",
      },
      {
        title: "User Consent",
        bullets: [
          "You voluntarily provide your personal information for BMI measurement and record keeping.",
          "You consent to the use of facial recognition for identifying returning users and retrieving previous records.",
          "You understand that the system will store and process your data securely for the purposes stated above.",
          "You acknowledge that participation in the system is voluntary, and you may decline to proceed if you do not agree with these terms.",
        ],
        paragraphs: ["If you do not agree with these Terms and Conditions, please discontinue the use of this system."],
      },
    ],
    [],
  );

  return (
    <div className="page-with-actions terms-page">
      <div className="screen-grid single-col">
        <div className="panel panel-large terms-panel">
          {typeof onBackToStart === "function" ? (
            <button className="btn terms-back-home-btn" onClick={onBackToStart}>
              Back to Start
            </button>
          ) : null}
          <div className="terms-content">
            <div className="terms-scroll">
              {termsSections.map((section, index) => (
                <section key={section.title} className="terms-section">
                  {index === 0 ? (
                    <h2 className="terms-main-title">{section.title}</h2>
                  ) : (
                    <h3 className="terms-sub-title">{section.title}</h3>
                  )}
                  {section.paragraphs?.map((paragraph) => (
                    <p key={paragraph} className="terms-paragraph">
                      {paragraph}
                    </p>
                  ))}
                  {section.bullets?.length ? (
                    <ul className="terms-list">
                      {section.bullets.map((item) => (
                        <li key={item}>{item}</li>
                      ))}
                    </ul>
                  ) : null}
                  {section.email ? (
                    <p className="terms-contact-email">
                      Email: <strong>{section.email}</strong>
                    </p>
                  ) : null}
                </section>
              ))}

            </div>
            <div className="terms-consent-block">
              <label className="checkbox-row">
                <input
                  type="checkbox"
                  checked={agree}
                  onChange={(event) => setAgree(event.target.checked)}
                />
                <span>
                  I have read and agree to the Terms and Conditions and consent to the secure processing of my personal
                  data.
                </span>
              </label>

              <div className="actions terms-actions-inline">
                {typeof onCancel === "function" ? (
                  <button className="btn" onClick={onCancel}>
                    Cancel
                  </button>
                ) : null}
                <button className="btn btn-danger" onClick={onDecline}>
                  Decline
                </button>
                <button className="btn btn-primary" disabled={!agree} onClick={onNext}>
                  Continue
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
